// Qt-only bridge that imports an explicitly attached or Codex-generated image
// and places it as a single-sided plane or on one native mesh face.
#pragma once
#include "MCPTextureTools.h"

namespace MCPImages {
inline void validateTarget(const QJsonObject& args,const MCPTextures::ServerCall& server)
{
	if(args.contains("target_uid"))
	{
		const double uid=MCPTextures::number(args,"target_uid",0,0,9007199254740991.0);
		if(uid!=std::floor(uid)) MCPTextures::fail("target_uid must be an integer.");
		if(!QStringList{"-X","+X","-Y","+Y","-Z","+Z"}.contains(args.value("face").toString())) MCPTextures::fail("Choose one object-local face: -X,+X,-Y,+Y,-Z,+Z.");
		server("get_object",{{"uid",uid}}); // Check the target before uploading.
	}
	else
	{
		if(args.contains("face")) MCPTextures::fail("face requires target_uid.");
		MCPTextures::number(args,"width",2,.01,100);
		MCPTextures::number(args,"angle",0,-1000,1000);
		if(args.contains("height")) MCPTextures::number(args,"height",2,.01,100);
		if(args.contains("pos"))
		{
			if(!args.value("pos").isObject()) MCPTextures::fail("pos must contain x,y,z.");
			const QJsonObject pos=args.value("pos").toObject();
			for(const char* axis:{"x","y","z"}) { if(!pos.contains(axis)) MCPTextures::fail("pos requires x,y,z.");MCPTextures::number(pos,axis,0,-1e7,1e7); }
		}
	}
}

inline QJsonObject place(const QJsonObject& args,const MCPTextures::ServerCall& server)
{
	validateTarget(args,server);
	QJsonObject image=MCPTextures::importImage(args,server);
	const QString texture=image.value("texture_url").toString();
	if(texture.isEmpty()) MCPTextures::fail("Image import returned no texture resource.");
	QJsonObject placement;
	if(args.contains("target_uid"))
		placement={{"replace_uid",args.value("target_uid")},{"texture_url",texture},{"face",args.value("face")}};
	else
	{
		const double width=MCPTextures::number(args,"width",2,.01,100);
		const double height=MCPTextures::number(args,"height",width*image.value("height").toDouble(1)/image.value("width").toDouble(1),.01,100);
		placement={{"texture_url",texture},{"width",width},{"height",height},{"double_sided",args.value("double_sided").toBool(false)}};
		for(const char* key:{"pos","angle"}) if(args.contains(key)) placement.insert(key,args.value(key));
	}
	image.insert("object",server(args.contains("target_uid")?"apply_image_texture":"create_image",placement));
	image.insert("applied",true);
	image.insert("generator","Codex built-in image generation or user-provided image");
	return image;
}

inline bool handles(const QString& name) { return name=="place_image"; }
inline QJsonObject call(const QString&,const QJsonObject& args,const MCPTextures::ServerCall& server) { return place(args,server); }
inline QJsonArray schemas()
{
	return {QJsonObject{{"name","place_image"},
		{"description","Import a user-attached image or the exact savedPath from Codex built-in image generation. Place it on one object-local face (use target_uid and face), which creates an independent face material/UV, or create a single-sided world image plane. Does not call an image API."},
		{"inputSchema",QJsonObject{{"type","object"},{"properties",QJsonObject{
			{"path",QJsonObject{{"type","string"},{"description","Exact path of an image attached by the user or just generated by Codex."}}},
			{"target_uid",QJsonObject{{"type","integer"},{"description","Optional editable native mesh UID. Omit to create a world plane."}}},
			{"face",QJsonObject{{"type","string"},{"enum",QJsonArray{"-X","+X","-Y","+Y","-Z","+Z"}}}},
			{"width",QJsonObject{{"type","number"},{"minimum",.01},{"maximum",100}}},
			{"height",QJsonObject{{"type","number"},{"minimum",.01},{"maximum",100},{"description","Defaults to the source image aspect ratio."}}},
			{"pos",QJsonObject{{"type","object"},{"properties",QJsonObject{{"x",QJsonObject{{"type","number"}}},{"y",QJsonObject{{"type","number"}}},{"z",QJsonObject{{"type","number"}}}}},{"required",QJsonArray{"x","y","z"}},{"additionalProperties",false}}},
			{"angle",QJsonObject{{"type","number"},{"description","World plane rotation about +Z in radians."}}},
			{"double_sided",QJsonObject{{"type","boolean"},{"default",false},{"description","For a new plane only; backface visibility is disabled by default."}}}
		}},{"required",QJsonArray{"path"}},{"additionalProperties",false}}}}};
}
}
