"""Embed existing library OBJ geometry for the server's MCP mesh builder.

Run from any directory; only webserver/MCPPrimitiveMeshes.h is generated.
No downloads or changes to original model resources.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = {
    "quad": "Quad", "capsule": "Capsule", "icosahedron": "Icosahedron", "icosphere": "Icosphere",
    "platonic_solid": "Platonic_Solid", "pyramid": "Pyramid",
    "octahedron": "Octahedron", "wedge": "Wedge",
    "triangular_prism": "Triangular_Prism", "hexagonal_prism": "Hexagonal_Prism",
}


def generate():
    out = ['// Generated by scripts/generate_mcp_primitive_meshes.py from resources/models/*.obj.',
           '// Native topology/normals; solids rotated Y-up to Z-up like native OBJ imports.',
           '// Centered and normalised to unit bounds per axis; quad remains in XY (+Z normal).',
           '#pragma once', '#include <cmath>', '#include <string>',
           'namespace MCPHandlers { namespace Modeling {',
           'template<class Builder> bool appendLibraryPrimitive(Builder& b, const std::string& name) {']
    for name, filename in MODELS.items():
        positions, normals, uvs, triangles = [], [], [], []
        for line in (ROOT / 'resources/models' / (filename + '.obj')).read_text().splitlines():
            fields = line.split()
            if not fields:
                continue
            if fields[0] == 'v':
                positions.append(tuple(map(float, fields[1:4])))
            elif fields[0] == 'vn':
                normals.append(tuple(map(float, fields[1:4])))
            elif fields[0] == 'vt':
                uvs.append(tuple(map(float, fields[1:3])))
            elif fields[0] == 'f':
                corners = []
                for field in fields[1:]:
                    indices = field.split('/')
                    corners.append((int(indices[0])-1, int(indices[2])-1 if len(indices)>2 and indices[2] else -1,
                                    int(indices[1])-1 if len(indices)>1 and indices[1] else -1))
                for i in range(1, len(corners)-1):
                    triangles.append((corners[0], corners[i], corners[i+1]))
        if name != 'quad':
            positions = [(v[0], -v[2], v[1]) for v in positions]
            normals = [(v[0], -v[2], v[1]) for v in normals]
        lo = [min(v[i] for v in positions) for i in range(3)]
        hi = [max(v[i] for v in positions) for i in range(3)]
        extent = [hi[i]-lo[i] or 1 for i in range(3)]
        vertices = [tuple((v[i]-(lo[i]+hi[i])/2)/extent[i] for i in range(3)) for v in positions]
        transformed_normals = [tuple(v[i]*extent[i] for i in range(3)) for v in normals]
        out.append(f'if(name=="{name}") {{ // {filename}.obj')
        for label, values in [('vertices', vertices), ('normals', [(0,0,0)]+transformed_normals)]:
            out.append(f'static const double {label}[][3]={{')
            out += ['{' + ','.join(format(x,'.10g') for x in v) + '},' for v in values]
            out.append('};')
        out.append('static const double uvs[][2]={')
        out += ['{' + ','.join(format(x,'.10g') for x in uv) + '},' for uv in uvs]
        out.append('};')
        out.append('static const int faces[][9]={')
        for face in triangles:
            if any(v<0 or v>=len(vertices) or n>=len(normals) or t<0 or t>=len(uvs) for v,n,t in face):
                raise ValueError(f'Invalid OBJ indices in {filename}')
            out.append('{' + ','.join(str(i) for v,n,t in face for i in (v,n+1,t)) + '},')
        out += ['};', 'for(const auto& f:faces) {',
                'Vec3d v[3],n[3]; for(int i=0;i<3;++i) {',
                'const double* p=vertices[f[i*3]]; const double* q=normals[f[i*3+1]];',
                'v[i]=Vec3d(p[0],p[1],p[2]); n[i]=Vec3d(q[0],q[1],q[2]); }',
                'const auto triangle_count=b.mesh.triangles.size();',
                'b.triangle(v[0],v[1],v[2],n[0],n[1],n[2]);',
                'if(b.mesh.triangles.size()==triangle_count+1) {',
                'const double* a=uvs[f[2]]; const double* c=uvs[f[5]]; const double* d=uvs[f[8]];',
                'b.setLastTriangleUV(a[0],a[1],c[0],c[1],d[0],d[1]);',
                '}', '}', 'return true; }']
    out += ['return false;', '}', '}}']
    (ROOT / 'webserver/MCPPrimitiveMeshes.h').write_text('\n'.join(out)+'\n', encoding='utf-8')


if __name__ == '__main__':
    generate()
