"""Generate, audit and render the local standard primitive library.

No network access. --write-models updates the seven procedural primitives;
--render writes PNG thumbnails rendered from each actual OBJ (requires Pillow).
The default audits geometry, outward winding, normals, UVs and manifold edges.
Source models are Y-up, matching the native OBJ importer's +90 degree X rotation.
"""
from __future__ import annotations

import argparse
from collections import Counter
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODEL_DIR = ROOT / "resources/models"
NAMES = ("Quad", "Cube", "Capsule", "Cylinder", "Icosahedron", "Platonic_Solid",
         "Torus", "Cone", "Pyramid", "Octahedron", "Wedge", "Triangular_Prism", "Hexagonal_Prism", "Icosphere")


def sub(a, b):
    return tuple(x-y for x, y in zip(a, b))


def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])


def dot(a, b):
    return sum(x*y for x, y in zip(a, b))


def unit(a):
    length = math.sqrt(dot(a, a))
    if length < 1e-12:
        raise ValueError("Zero-length normal")
    return tuple(x/length for x in a)


def read_obj(path):
    positions, normals, uvs, faces = [], [], [], []
    for line in path.read_text(encoding="utf-8").splitlines():
        fields = line.split()
        if not fields:
            continue
        if fields[0] == "v":
            positions.append(tuple(map(float, fields[1:4])))
        elif fields[0] == "vn":
            normals.append(tuple(map(float, fields[1:4])))
        elif fields[0] == "vt":
            uvs.append(tuple(map(float, fields[1:3])))
        elif fields[0] == "f":
            face = []
            for corner in fields[1:]:
                indices = corner.split("/")
                face.append(tuple(int(indices[i])-1 if i < len(indices) and indices[i] else -1 for i in range(3)))
            faces.append(face)
    return positions, normals, uvs, faces


def triangles(faces):
    for face in faces:
        for i in range(1, len(face)-1):
            yield (face[0], face[i], face[i+1])


def write_obj(name, positions, faces, smooth_cone=False):
    """Write shared positions with per-corner UVs/normals and sharp cap seams."""
    lines = ["# MetaSiberia standard primitive; generated by scripts/standard_primitive_library.py.",
             "# Y-up, counter-clockwise outside, explicit UVs and normals.", "o " + name, "usemtl default"]
    lines += ["v " + " ".join(f"{x:.10g}" for x in p) for p in positions]
    corners, cursor = [], 1
    for face in faces:
        normal = unit(cross(sub(positions[face[1]], positions[face[0]]), sub(positions[face[2]], positions[face[0]])))
        u_axis = unit(sub(positions[face[1]], positions[face[0]]))
        v_axis = cross(normal, u_axis)
        projected = [(dot(positions[index], u_axis), dot(positions[index], v_axis)) for index in face]
        lo = tuple(min(p[a] for p in projected) for a in range(2))
        hi = tuple(max(p[a] for p in projected) for a in range(2))
        cone_uvs = None
        if smooth_cone and face[0] == 0:
            side_u = [math.atan2(positions[index][2], positions[index][0])/(2*math.pi) % 1 for index in face[1:]]
            if max(side_u)-min(side_u) > 0.5:
                side_u = [u+1 if u < 0.5 else u for u in side_u]
            cone_uvs = [(sum(side_u)/2, 1), (side_u[0], 0), (side_u[1], 0)]
        face_corners = []
        for corner, (index, uv) in enumerate(zip(face, projected)):
            n = normal
            if smooth_cone and face[0] == 0:
                p = positions[index]
                n = unit((p[0], 0.25, p[2])) if index != 0 else normal
            uv = tuple((uv[a]-lo[a])/(hi[a]-lo[a] or 1) for a in range(2))
            if smooth_cone:
                uv = cone_uvs[corner] if cone_uvs else (positions[index][0]+0.5, positions[index][2]+0.5)
            lines.append("vt " + " ".join(f"{x:.10g}" for x in uv))
            lines.append("vn " + " ".join(f"{x:.10g}" for x in n))
            face_corners.append(f"{index+1}/{cursor}/{cursor}")
            cursor += 1
        corners.append("f " + " ".join(face_corners))
    lines.extend(corners)
    (MODEL_DIR / (name + ".obj")).write_text("\n".join(lines)+"\n", encoding="utf-8")


def generate_models():
    # Retain the original subdivided sphere as its correctly named own primitive.
    icosphere_path = MODEL_DIR / "Icosphere.obj"
    if not icosphere_path.exists():
        source = MODEL_DIR / "Icosahedron.obj"
        assert len(read_obj(source)[0]) == 162, "Original Icosphere resource is missing"
        icosphere_path.write_bytes(source.read_bytes())
    # A regular icosahedron has 12 vertices and exactly 20 flat triangular faces.
    phi = (1+math.sqrt(5))/2
    radius_scale = 0.5/math.sqrt(1+phi*phi)
    positions = []
    for a in (-1, 1):
        for b in (-phi, phi):
            positions.extend([(0, a*radius_scale, b*radius_scale), (a*radius_scale, b*radius_scale, 0), (b*radius_scale, 0, a*radius_scale)])
    faces = []
    from itertools import combinations
    for a, b, c in combinations(range(len(positions)), 3):
        normal = cross(sub(positions[b], positions[a]), sub(positions[c], positions[a]))
        sides = [dot(normal, sub(p, positions[a])) for p in positions]
        if min(sides) < -1e-8 and max(sides) > 1e-8:
            continue
        faces.append([a, b, c] if dot(normal, positions[a]) > 0 else [a, c, b])
    assert len(faces) == 20
    write_obj("Icosahedron", positions, faces)
    # Preserve the established source coordinates and topology of the polyhedra.
    for name in ("Pyramid", "Octahedron", "Wedge", "Triangular_Prism", "Hexagonal_Prism"):
        positions, _, _, faces = read_obj(MODEL_DIR / (name + ".obj"))
        write_obj(name, positions, [[corner[0] for corner in face] for face in faces])
    # A cone is rotationally smooth; the previous eight-sided stand-in was faceted.
    segments = 48
    positions = [(0, 0.5, 0), (0, -0.5, 0)]
    positions += [(0.5*math.cos(2*math.pi*i/segments), -0.5, 0.5*math.sin(2*math.pi*i/segments)) for i in range(segments)]
    faces = []
    for i in range(segments):
        current, following = i+2, (i+1) % segments+2
        faces += [[0, following, current], [1, current, following]]
    write_obj("Cone", positions, faces, smooth_cone=True)


def audit(name):
    positions, normals, uvs, faces = read_obj(MODEL_DIR / (name + ".obj"))
    assert positions and faces, name + ": empty geometry"
    assert all(math.isfinite(x) for collection in (positions, normals, uvs) for p in collection for x in p), name + ": non-finite attribute"
    # Some original exports duplicate seam vertices: validate geometric edges.
    weld = {}
    vertex_ids = [weld.setdefault(tuple(round(x, 6) for x in p), len(weld)) for p in positions]
    edges, directed = Counter(), Counter()
    volume = 0
    count = 0
    for face in triangles(faces):
        assert all(0 <= c[0] < len(positions) and 0 <= c[1] < len(uvs) and 0 <= c[2] < len(normals) for c in face), name + ": missing or invalid OBJ attributes"
        a, b, c = [positions[corner[0]] for corner in face]
        normal = cross(sub(b, a), sub(c, a))
        assert dot(normal, normal) > 1e-20, name + ": degenerate triangle"
        assert all(dot(normal, normals[corner[2]]) > 0 for corner in face), name + ": normal disagrees with face winding"
        volume += dot(a, cross(b, c))/6
        count += 1
        ids = [vertex_ids[corner[0]] for corner in face]
        for i in range(3):
            edge = (ids[i], ids[(i+1) % 3])
            edges[tuple(sorted(edge))] += 1
            directed[edge] += 1
    if name == "Quad":
        assert count == 2 and sum(value == 1 for value in edges.values()) == 4
    else:
        assert volume > 0, name + ": inward winding or empty volume"
        assert all(value == 2 for value in edges.values()), name + ": non-manifold or open surface"
        assert all(directed[(b, a)] == count for (a, b), count in directed.items()), name + ": inconsistent shared edge direction"
    expected = {"Quad": (4, 2), "Cube": (8, 12), "Capsule": (830, 1656), "Cylinder": (74, 144),
                "Icosahedron": (12, 20), "Icosphere": (162, 320), "Platonic_Solid": (20, 36),
                "Torus": (648, 1296), "Cone": (50, 96), "Pyramid": (5, 6), "Octahedron": (6, 8),
                "Wedge": (6, 8), "Triangular_Prism": (6, 8), "Hexagonal_Prism": (12, 20)}
    assert (len(weld), count) == expected[name], name + ": unexpected primitive topology"
    print(f"{name}: {len(weld)} geometric vertices, {count} triangles, volume={volume:.6g}: OK")


def render(name, size=240):
    """Deterministic orthographic software rendering of the actual OBJ triangles.

    Z buffer and barycentrically interpolated OBJ normals preserve curved surfaces
    and sharp edges. No proxy geometry, image generation or external model assets.
    """
    from PIL import Image
    positions, normals, _, faces = read_obj(MODEL_DIR / (name + ".obj"))
    scale = 3  # supersampling for silhouettes
    width = height = size*scale
    eye = unit((2.8, 2.1, 4.0))
    right = unit(cross((0, 1, 0), eye))
    up = cross(eye, right)
    lo = [min(p[i] for p in positions) for i in range(3)]
    hi = [max(p[i] for p in positions) for i in range(3)]
    centre = [(a+b)/2 for a, b in zip(lo, hi)]
    span = max(b-a for a, b in zip(lo, hi))
    transformed = [tuple((x-c)/span for x, c in zip(p, centre)) for p in positions]
    camera_positions = [(dot(p, right), dot(p, up), dot(p, eye)) for p in transformed]
    camera_lo = [min(p[i] for p in camera_positions) for i in range(2)]
    camera_hi = [max(p[i] for p in camera_positions) for i in range(2)]
    fit = 0.80/max(camera_hi[i]-camera_lo[i] for i in range(2))
    camera_centre = [(camera_lo[i]+camera_hi[i])/2 for i in range(2)]
    projected = [(width*(0.5+fit*(p[0]-camera_centre[0])), height*(0.5-fit*(p[1]-camera_centre[1])), p[2]) for p in camera_positions]
    image = Image.new("RGB", (width, height), (67, 74, 80))
    pixels = image.load()
    depth = [-math.inf]*(width*height)
    light = unit((-3, 6, 5))
    fill = unit((4, 2, -3))
    for face in triangles(faces):
        vertices = [projected[c[0]] for c in face]
        face_normal = cross(sub(transformed[face[1][0]], transformed[face[0][0]]), sub(transformed[face[2][0]], transformed[face[0][0]]))
        if dot(face_normal, eye) <= 0:
            continue
        ns = [normals[c[2]] if c[2] >= 0 else unit(face_normal) for c in face]
        a, b, c = vertices
        denominator = (b[1]-c[1])*(a[0]-c[0])+(c[0]-b[0])*(a[1]-c[1])
        if abs(denominator) < 1e-10:
            continue
        for y in range(max(0, int(min(v[1] for v in vertices))), min(height, math.ceil(max(v[1] for v in vertices))+1)):
            for x in range(max(0, int(min(v[0] for v in vertices))), min(width, math.ceil(max(v[0] for v in vertices))+1)):
                u = ((b[1]-c[1])*(x+0.5-c[0])+(c[0]-b[0])*(y+0.5-c[1]))/denominator
                v = ((c[1]-a[1])*(x+0.5-c[0])+(a[0]-c[0])*(y+0.5-c[1]))/denominator
                w = 1-u-v
                if min(u, v, w) < -1e-8:
                    continue
                z = u*a[2]+v*b[2]+w*c[2]
                index = y*width+x
                if z <= depth[index]:
                    continue
                depth[index] = z
                n = unit(tuple(u*ns[0][i]+v*ns[1][i]+w*ns[2][i] for i in range(3)))
                brightness = 0.30+0.60*max(0, dot(n, light))+0.10*max(0, dot(n, fill))
                pixels[x, y] = tuple(int(channel*brightness) for channel in (225, 229, 235))
    # Keep the original lowercase quad filename for case-sensitive distributions.
    image = image.resize((size, size), Image.Resampling.LANCZOS)
    image.save(MODEL_DIR / ("quad.PNG" if name == "Quad" else name + ".PNG"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-models", action="store_true")
    parser.add_argument("--render", action="store_true")
    args = parser.parse_args()
    if args.write_models:
        generate_models()
    for name in NAMES:
        audit(name)
        if args.render:
            render(name)


if __name__ == "__main__":
    main()
