// Standalone mathematical checks; no world access, production resources or project dependencies.
// clang++ -std=c++17 -O2 scripts/test_mcp_mesh_operations.cpp -o <temporary-path>
#include "../webserver/MCPMeshOperations.h"
#include <cassert>
#include <iostream>

using namespace MCPMeshOps;

static Mesh box(Vec3 lo,Vec3 hi,unsigned material) {
	const Vec3 p[]={Vec3(lo.x,lo.y,lo.z),Vec3(hi.x,lo.y,lo.z),Vec3(hi.x,hi.y,lo.z),Vec3(lo.x,hi.y,lo.z),
		Vec3(lo.x,lo.y,hi.z),Vec3(hi.x,lo.y,hi.z),Vec3(hi.x,hi.y,hi.z),Vec3(lo.x,hi.y,hi.z)};
	const int f[][4]={{0,3,2,1},{4,5,6,7},{0,1,5,4},{1,2,6,5},{2,3,7,6},{3,0,4,7}};
	Mesh mesh;
	for(const auto& face:f) for(int j=1;j<3;++j) {
		Triangle t;t.material=material;const int id[]={face[0],face[j],face[j+1]};const Vec3 n=unit(cross(p[id[1]]-p[id[0]],p[id[2]]-p[id[0]]));
		for(int k=0;k<3;++k) { Vertex& v=t.vertices[k];v.position=p[id[k]];v.normal=n;v.u=v.position.x+2*v.position.z;v.v=v.position.y+3*v.position.z; }mesh.push_back(t);
	}
	return mesh;
}
static bool close(double x,double y,double eps=1e-7) { return std::abs(x-y)<eps; }
static void checkUV(const Mesh& m) {
	for(const Triangle& t:m) for(const Vertex& v:t.vertices) { assert(close(v.u,v.position.x+2*v.position.z));assert(close(v.v,v.position.y+3*v.position.z));assert(close(length(v.normal),1)); }
}
static void checkVolume(const Mesh& m,double value) { validateClosed(m);assert(close(signedVolume(m),value));checkUV(m); }
template<class F> static void rejects(F f) { bool threw=false;try { f(); }catch(const std::runtime_error&) { threw=true; }assert(threw); }

int main() {
	const Mesh a=box(Vec3(0,0,0),Vec3(2,2,2),1),b=box(Vec3(1,0,0),Vec3(3,2,2),2);
	checkVolume(a,8);checkVolume(b,8);
	checkVolume(booleanMesh(a,b,"union"),12);checkVolume(booleanMesh(a,b,"subtract"),4);checkVolume(booleanMesh(a,b,"intersect"),4);
	const Mesh sub=booleanMesh(a,b,"subtract");bool original=false,cut=false;
	for(const Triangle& t:sub) { original|=t.material==1;cut|=t.material==2;assert(t.material==1||t.material==2); }
	assert(original&&cut);
	checkVolume(booleanMesh(a,a,"union"),8);checkVolume(booleanMesh(a,a,"intersect"),8);assert(booleanMesh(a,a,"subtract").empty());
	const Mesh small=box(Vec3(.5,.5,.5),Vec3(1.5,1.5,1.5),3);
	checkVolume(booleanMesh(a,small,"subtract"),7);checkVolume(booleanMesh(a,small,"union"),8);checkVolume(booleanMesh(a,small,"intersect"),1);
	const Mesh disjoint=box(Vec3(3,0,0),Vec3(4,1,1),2);
	checkVolume(booleanMesh(a,disjoint,"union"),9);checkVolume(booleanMesh(a,disjoint,"subtract"),8);assert(booleanMesh(a,disjoint,"intersect").empty());
	const Mesh touching=box(Vec3(2,0,0),Vec3(3,2,2),2);
	checkVolume(booleanMesh(a,touching,"union"),12);assert(booleanMesh(a,touching,"intersect").empty());
	const Mesh diagonal=box(Vec3(1,1,1),Vec3(3,3,3),2);
	checkVolume(booleanMesh(a,diagonal,"union"),15);checkVolume(booleanMesh(a,diagonal,"subtract"),7);checkVolume(booleanMesh(a,diagonal,"intersect"),1);
	Mesh open=a;open.pop_back();rejects([&]{booleanMesh(open,b,"union");});
	Mesh reverse=a;for(Triangle& t:reverse) std::swap(t.vertices[0],t.vertices[1]);rejects([&]{booleanMesh(reverse,b,"union");});
	Mesh duplicate=a;duplicate.push_back(a[0]);rejects([&]{booleanMesh(duplicate,b,"union");});
	rejects([&]{booleanMesh(a,b,"invalid");});
	Mesh nonfinite=a;nonfinite[0].vertices[0].u=std::nan("");rejects([&]{booleanMesh(nonfinite,b,"union");});
	Mesh overlapping_shells=a;overlapping_shells.insert(overlapping_shells.end(),diagonal.begin(),diagonal.end());rejects([&]{booleanMesh(overlapping_shells,b,"union");});
	Mesh nested_outward=a;nested_outward.insert(nested_outward.end(),small.begin(),small.end());rejects([&]{booleanMesh(nested_outward,b,"union");});
	Mesh inverted_shell=disjoint;for(Triangle& t:inverted_shell) std::swap(t.vertices[0],t.vertices[1]);inverted_shell.insert(inverted_shell.end(),a.begin(),a.end());rejects([&]{booleanMesh(inverted_shell,b,"union");});
	Mesh touching_point=box(Vec3(2,2,2),Vec3(3,3,3),1);touching_point.insert(touching_point.end(),a.begin(),a.end());rejects([&]{booleanMesh(touching_point,b,"union");});
	// Deterministic varied overlaps and chained CSG, including seam vertices generated by the first operation.
	for(int k=0;k<24;++k) {
		const double x=-.7+k*.13,y=.1+(k%5)*.2,z=-.3+(k%7)*.17;
		const Mesh operand=box(Vec3(x,y,z),Vec3(x+1.3,y+1.1,z+1.7),2);
		const double ix=std::max(0.0,std::min(2.0,x+1.3)-std::max(0.0,x)),iy=std::max(0.0,std::min(2.0,y+1.1)-std::max(0.0,y)),iz=std::max(0.0,std::min(2.0,z+1.7)-std::max(0.0,z));
		const Mesh u=booleanMesh(a,operand,"union"),s=booleanMesh(a,operand,"subtract"),in=booleanMesh(a,operand,"intersect");
		assert(close(signedVolume(u),8+1.3*1.1*1.7-ix*iy*iz));assert(close(signedVolume(s),8-ix*iy*iz));assert(close(signedVolume(in),ix*iy*iz));
		checkUV(u);checkUV(s);checkUV(in);
	}
	checkVolume(booleanMesh(booleanMesh(a,small,"subtract"),b,"intersect"),3.5);
	// Rotated noncoplanar cuts: mass identities hold independently of the intersection shape.
	Mesh rotated=box(Vec3(-.5,-.5,-.5),Vec3(.5,.5,.5),5);
	const double ca=std::cos(.37),sa=std::sin(.37);
	for(Triangle& t:rotated) for(Vertex& v:t.vertices) {
		const Vec3 p=v.position,n=v.normal;
		v.position=Vec3(1.7+ca*p.x-sa*p.y,1+sa*p.x+ca*p.y,1+p.z);
		v.normal=Vec3(ca*n.x-sa*n.y,sa*n.x+ca*n.y,n.z);
	}
	const Mesh ru=booleanMesh(a,rotated,"union"),rs=booleanMesh(a,rotated,"subtract"),ri=booleanMesh(a,rotated,"intersect");
	assert(close(signedVolume(ru)+signedVolume(ri),9));assert(close(signedVolume(rs)+signedVolume(ri),8));
	Mesh bevel=bevelBox(Vec3(2,3,4),.2,7,8);validateClosed(bevel);assert(signedVolume(bevel)>20&&signedVolume(bevel)<24);
	assert(close(signedVolume(bevelBox(Vec3(1,1,1),.1)),1-6*.1*.1+16.0/3*.1*.1*.1));
	bool flat=false,beveled=false;
	for(const Triangle& t:bevel) { flat|=t.material==7;beveled|=t.material==8;for(const Vertex& v:t.vertices) { assert(std::abs(v.position.x)<=1.000001);assert(std::abs(v.position.y)<=1.500001);assert(std::abs(v.position.z)<=2.000001);assert(close(length(v.normal),1)); } }
	assert(flat&&beveled);rejects([&]{bevelBox(Vec3(1,1,1),.5);});
	Deformation op;op.mode="push";op.radius=10;op.strength=.1;
	Mesh moved=deformMesh(a,op);validateClosed(moved);for(size_t i=0;i<a.size();++i) for(int j=0;j<3;++j) { assert(moved[i].vertices[j].position.z>a[i].vertices[j].position.z);assert(moved[i].vertices[j].u==a[i].vertices[j].u);assert(moved[i].material==a[i].material); }
	op.mode="inflate";validateClosed(deformMesh(a,op));assert(signedVolume(deformMesh(a,op))>8);
	op.mode="smooth";op.strength=.1;validateClosed(deformMesh(a,op));assert(signedVolume(deformMesh(a,op))<8);
	op.mode="twist";op.min=0;op.max=2;op.amount=.2;validateClosed(deformMesh(a,op));
	op.mode="taper";op.amount=.25;validateClosed(deformMesh(a,op));assert(signedVolume(deformMesh(a,op))>8);
	op.amount=-1;rejects([&]{deformMesh(a,op);});
	std::cout<<"MCP mesh operations: Boolean volumes/topology/UV/materials, empty/contact cases, invalid inputs, bevel and deformations passed.\n";
}
